name: daily-report

on:
<<<<<<< HEAD
   schedule:
     - cron: '*/5 * * * *'
=======
  schedule:
    - cron: '*/5 * * * *'
>>>>>>> 3b3c7539043c73654699f7a11138bb9492eaf27f
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py
